import Mathlib

/-!
# Census sample: 2,000 Mathlib theorems with at least two hypotheses

Run on the build box with
`ANCHOR_CENSUS_OUT=<dir> lake env lean AnchorTest/Census/MathlibSample.lean`.
It writes three files into `<dir>` (default `AnchorTest/Census`):

* `mathlib_sample_2000.tsv`: the sample, one row per theorem, with the columns
  name, module, stratum, hypotheses, model_binders, dependent.
* `mathlib_sample_summary.txt`: the frame summary and the rules below, with counts.
* `mathlib_frame.tsv`: the whole frame with each name's SHA-256, so the selection can be
  recomputed outside Lean.

## Hypotheses

The leading binders of a theorem's type are walked with `forallTelescope`, which does not
unfold definitions. A binder whose type is a Prop is a hypothesis; every other binder is part
of the model. A Prop-valued instance binder such as `[Fact (1 < p)]` is a Prop binder, so it
counts as a hypothesis. The rest of the type is the conclusion. A statement is dependent when
a hypothesis variable occurs in the type of a later binder or in the conclusion.

## Which constants are scanned

Every theorem declared in a module whose name starts with `Mathlib.`. A theorem is left out
when any of these holds, checked in this order:

1. Internal or private name: some prefix of the name satisfies `Lean.Name.isInternalDetail`
   (a component starting with `_`, a numeric component, or a component `eq_<n>`, `match_<n>`,
   `proof_<n>`, `omega_<n>`), or `Lean.isPrivateName`. This covers `_private`, `_proof_`,
   `.proof_<n>`, `match_<n>` and its equations, `_simp_<n>`, `_auxLemma`, `_sunfold` and
   `eq_<n>`.
2. Generated by the elaborator: `Lean.isReservedName` (equation lemmas such as `eq_def` and
   `   eq_unfold`, functional induction, `congr_simp`, matcher equations), an auxiliary recursor
   or `noConfusion` (`Lean.isAuxRecursor`, `Lean.isNoConfusion`), a last component `brecOn` or
   `binductionOn` whose prefix is an inductive type (for an inductive predicate these are
   theorems, and `isAuxRecursor` does not mark them), or a last component `injEq`, `inj` or
   `sizeOf_spec` whose prefix is a constructor.
3. An instance (`Lean.Meta.isInstanceCore`).
4. A type that is not a Prop.
5. Classification raised an error or ran out of heartbeats (200,000 per theorem).

The substrings `eq_` and `_spec` are not exclusion rules by themselves: ordinary lemmas such as
`mul_eq_zero` and `Classical.choose_spec` contain them. Only the generated forms above go.
Lemmas produced by Mathlib attributes (`to_additive`, `simps`, `ext`, `reassoc`) and deprecated
aliases stay in; the summary counts the deprecated ones.

## Stratification and allocation

The stratum is the second component of the module name (`Mathlib.Algebra.Group.Basic` is in
`Algebra`). The frame is the eligible theorems with at least two hypotheses. With frame size
`N`, stratum sizes `n_s` and total `T = 2000`:

1. Every stratum has the floor `f_s = min(10, n_s)`.
2. Let `B` be `T` minus the floors of the strata already held, and `P` the total size of the
   strata not held. A stratum not held whose share `B n_s / P` is below `f_s` is held at
   `f_s`. Repeat until no stratum is added.
3. The strata not held get `⌊B n_s / P⌋` each, and the units left over go one each to the
   largest remainders `B n_s mod P` (ties: larger stratum, then stratum name).

The units the small strata receive above their proportional share therefore come out of the
other strata in proportion to their size, so the largest strata give up the most.

## Selection

Within a stratum the theorems are ranked by the SHA-256 digest (FIPS 180-4, implemented below
and checked against three standard test vectors on every run) of the UTF-8 bytes of the name
exactly as printed in the `name` column (Lean's `Name.toString`), lowest first, with no salt.
The lowest `a_s` are taken. Anyone can recompute a digest with
`printf '%s' NAME | sha256sum`. Rows are written in order of stratum name, then digest.
-/

open Lean Meta

namespace AnchorTest.Census.MathlibSample

/-! ## SHA-256 -/

/-- The 64 round constants of SHA-256. -/
def sha256K : Array UInt32 := #[
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
  0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
  0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
  0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
  0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
  0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2]

/-- The initial hash value of SHA-256. -/
def sha256H0 : Array UInt32 := #[
  0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19]

/-- Rotate right by `n` bits, `0 < n < 32`. -/
@[inline] def rotr (x n : UInt32) : UInt32 := (x >>> n) ||| (x <<< (32 - n))

/-- Append `0x80`, zeros, and the bit length as a big-endian 64-bit integer, so the length is
a multiple of 64 bytes. -/
def sha256Pad (msg : ByteArray) : ByteArray := Id.run do
  let bitLen : UInt64 := msg.size.toUInt64 * 8
  let mut b := msg.push 0x80
  while b.size % 64 != 56 do
    b := b.push 0
  for i in [0:8] do
    b := b.push (bitLen >>> (8 * (7 - i)).toUInt64).toUInt8
  return b

/-- Process the 64-byte block of `blk` starting at `off`. -/
def sha256Block (h : Array UInt32) (blk : ByteArray) (off : Nat) : Array UInt32 := Id.run do
  let mut w : Array UInt32 := #[]
  for t in [0:16] do
    let i := off + 4 * t
    w := w.push ((blk[i]!.toUInt32 <<< 24) ||| (blk[i+1]!.toUInt32 <<< 16) |||
      (blk[i+2]!.toUInt32 <<< 8) ||| blk[i+3]!.toUInt32)
  for t in [16:64] do
    let x := w[t-15]!
    let y := w[t-2]!
    let s0 := (rotr x 7) ^^^ (rotr x 18) ^^^ (x >>> 3)
    let s1 := (rotr y 17) ^^^ (rotr y 19) ^^^ (y >>> 10)
    w := w.push (w[t-16]! + s0 + w[t-7]! + s1)
  let mut va := h[0]!
  let mut vb := h[1]!
  let mut vc := h[2]!
  let mut vd := h[3]!
  let mut ve := h[4]!
  let mut vf := h[5]!
  let mut vg := h[6]!
  let mut vh := h[7]!
  for t in [0:64] do
    let s1 := (rotr ve 6) ^^^ (rotr ve 11) ^^^ (rotr ve 25)
    let ch := (ve &&& vf) ^^^ ((~~~ve) &&& vg)
    let t1 := vh + s1 + ch + sha256K[t]! + w[t]!
    let s0 := (rotr va 2) ^^^ (rotr va 13) ^^^ (rotr va 22)
    let maj := (va &&& vb) ^^^ (va &&& vc) ^^^ (vb &&& vc)
    let t2 := s0 + maj
    vh := vg
    vg := vf
    vf := ve
    ve := vd + t1
    vd := vc
    vc := vb
    vb := va
    va := t1 + t2
  return #[h[0]! + va, h[1]! + vb, h[2]! + vc, h[3]! + vd,
    h[4]! + ve, h[5]! + vf, h[6]! + vg, h[7]! + vh]

/-- Eight lowercase hexadecimal digits. -/
def hex8 (w : UInt32) : String :=
  let ds := Nat.toDigits 16 w.toNat
  (List.replicate (8 - ds.length) '0' ++ ds).foldl String.push ""

/-- The SHA-256 digest of the UTF-8 bytes of `s`, as 64 lowercase hexadecimal digits. -/
def sha256Hex (s : String) : String := Id.run do
  let p := sha256Pad s.toUTF8
  let mut h := sha256H0
  for k in [0:p.size / 64] do
    h := sha256Block h p (64 * k)
  return h.foldl (fun acc w => acc ++ hex8 w) ""

/-- Standard test vectors: the empty string, `abc`, and a 56-byte message that needs two
blocks. -/
def sha256Vectors : List (String × String) := [
  ("", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"),
  ("abc", "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"),
  ("abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq",
    "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1")]

/-! ## Exclusion rules -/

/-- `f` holds of some prefix of the name, the name itself included. -/
def anyPrefix (f : Name → Bool) : Name → Bool
  | .anonymous => false
  | n@(.str p _) => f n || anyPrefix f p
  | n@(.num p _) => f n || anyPrefix f p

/-- Rule 1: an internal or private name. -/
def internalName (n : Name) : Bool :=
  anyPrefix Name.isInternalDetail n || isPrivateName n

/-- Rule 2: a theorem the elaborator generated. -/
def generatedName (env : Environment) (n : Name) : Bool :=
  isReservedName env n || isAuxRecursor env n || isNoConfusion env n ||
    match n with
    | .str p s =>
      ((s == "injEq" || s == "inj" || s == "sizeOf_spec") && env.isConstructor p) ||
        ((s == "brecOn" || s == "binductionOn") && env.find? p matches some (.inductInfo _))
    | _ => false

/-- `s` with its decimal digits removed, or `<num>` when nothing is left. -/
def stripDigits (s : String) : String :=
  let t := (s.toList.filter fun c => !c.isDigit).foldl String.push ""
  if t.isEmpty then "<num>" else t

/-- The component that makes a name internal, digits removed, for the summary. -/
def internalReason (n : Name) : String :=
  if isPrivateName n then "_private" else
    match n.components.find? Name.isInternalDetail with
    | some c => stripDigits (toString c)
    | none => "other"

/-- The last component, digits removed, for the summary. -/
def lastReason (n : Name) : String :=
  match n with
  | .str _ s => stripDigits s
  | _ => "<num>"

/-! ## Classification -/

/-- What the census records about one statement. -/
structure Shape where
  hyps : Nat
  model : Nat
  dependent : Bool
  /-- Hypotheses that are instance-implicit binders. -/
  instHyps : Nat
  deriving Inhabited

/-- `none` when the type is not a Prop. -/
def classify (ty : Expr) : MetaM (Option Shape) := do
  unless (← isProp ty) do return none
  forallTelescope ty fun xs body => do
    let mut hyps := 0
    let mut model := 0
    let mut inst := 0
    let mut dep := false
    let mut hypIds : Array FVarId := #[]
    for x in xs do
      let decl ← x.fvarId!.getDecl
      let xty := decl.type
      if !dep && hypIds.any (fun h => xty.containsFVar h) then
        dep := true
      if (← isProp xty) then
        hyps := hyps + 1
        hypIds := hypIds.push x.fvarId!
        if decl.binderInfo.isInstImplicit then
          inst := inst + 1
      else
        model := model + 1
    if !dep && hypIds.any (fun h => body.containsFVar h) then
      dep := true
    return some { hyps, model, dependent := dep, instHyps := inst }

/-- One theorem of the frame. -/
structure Row where
  name : String
  module : String
  stratum : String
  shape : Shape
  digest : String
  deprecated : Bool
  noRange : Bool
  lastComp : String
  deriving Inhabited

def Row.tsv (r : Row) : String :=
  s!"{r.name}\t{r.module}\t{r.stratum}\t{r.shape.hyps}\t{r.shape.model}\t{r.shape.dependent}"

/-- Order by stratum, then digest, then name. -/
def Row.lt (a b : Row) : Bool :=
  a.stratum < b.stratum || (a.stratum == b.stratum &&
    (a.digest < b.digest || (a.digest == b.digest && a.name < b.name)))

/-! ## Allocation -/

/-- Tie order for allocation: larger stratum first, then stratum name. -/
def before (sizes : Array (String × Nat)) (i j : Nat) : Bool :=
  sizes[i]!.2 > sizes[j]!.2 || (sizes[i]!.2 == sizes[j]!.2 && sizes[i]!.1 < sizes[j]!.1)

/-- Units left for the strata not yet held at their floor, and their total size. -/
def budgetPool (sizes : Array (String × Nat)) (floors : Array Nat) (fixed : Array Bool)
    (total : Nat) : Nat × Nat :=
  (Array.range sizes.size).foldl (init := (total, 0)) fun (b, p) i =>
    if fixed[i]! then (b - floors[i]!, p) else (b, p + sizes[i]!.2)

/-- Allocate `total` over strata of the given sizes by the rule in the module header. -/
def allocate (sizes : Array (String × Nat)) (total floorMin : Nat) : Array Nat := Id.run do
  let floors := sizes.map fun s => min floorMin s.2
  let mut fixed : Array Bool := sizes.map fun _ => false
  let mut changed := true
  while changed do
    changed := false
    let (budget, pool) := budgetPool sizes floors fixed total
    for i in [0:sizes.size] do
      if !fixed[i]! && budget * sizes[i]!.2 < floors[i]! * pool then
        fixed := fixed.modify i fun _ => true
        changed := true
  let (budget, pool) := budgetPool sizes floors fixed total
  let free := (Array.range sizes.size).filter fun i => !fixed[i]!
  let mut a : Array Nat := (Array.range sizes.size).map fun i =>
    if fixed[i]! then floors[i]! else budget * sizes[i]!.2 / pool
  let leftover := budget - free.foldl (fun acc i => acc + a[i]!) 0
  let rem (i : Nat) : Nat := budget * sizes[i]!.2 % pool
  let order := free.qsort fun i j => rem i > rem j || (rem i == rem j && before sizes i j)
  for k in [0:min leftover order.size] do
    a := a.modify order[k]! (· + 1)
  return a

/-! ## Reporting helpers -/

/-- `k/n` as a percentage with two decimals, rounded half up. -/
def pct (k n : Nat) : String :=
  if n == 0 then "n/a" else
    let x := (k * 10000 + n / 2) / n
    let frac := x % 100
    s!"{x / 100}.{if frac < 10 then "0" else ""}{frac}%"

def frac (k n : Nat) : String := s!"{k}/{n} = {pct k n}"

/-- Left-justify `s` in a field of width `w`. -/
def padR (s : String) (w : Nat) : String := s.pushn ' ' (w - s.length)

/-- Right-justify `s` in a field of width `w`. -/
def padL (s : String) (w : Nat) : String := "".pushn ' ' (w - s.length) ++ s

/-! ## The run -/

def sampleTotal : Nat := 2000
def stratumFloor : Nat := 10

def run : CoreM Unit := do
  for (msg, want) in sha256Vectors do
    let got := sha256Hex msg
    unless got == want do
      throwError "SHA-256 self-test failed on {repr msg}: got {got}, want {want}"
  let env ← getEnv
  let mods := env.header.moduleNames
  let mdata := env.header.moduleData
  let mut modsScanned := 0
  let mut constsScanned := 0
  let mut thmsScanned := 0
  let mut exInternal := 0
  let mut exGenerated := 0
  let mut exInstance := 0
  let mut exNotProp := 0
  let mut exError := 0
  let mut errNames : Array String := #[]
  let mut hist : Array Nat := Array.replicate 6 0
  let mut internalTally : Std.HashMap String Nat := {}
  let mut generatedTally : Std.HashMap String Nat := {}
  let mut unsorted : Array Row := #[]
  for i in [0:mods.size] do
    let mod := mods[i]!
    let comps := mod.components
    unless mod.getRoot == `Mathlib && comps.length ≥ 2 do continue
    modsScanned := modsScanned + 1
    let stratum := toString comps[1]!
    for n in mdata[i]!.constNames do
      constsScanned := constsScanned + 1
      let some (.thmInfo tv) := env.find? n | continue
      thmsScanned := thmsScanned + 1
      if internalName n then
        exInternal := exInternal + 1
        let k := internalReason n
        internalTally := internalTally.insert k (internalTally.getD k 0 + 1)
        continue
      if generatedName env n then
        exGenerated := exGenerated + 1
        let k := lastReason n
        generatedTally := generatedTally.insert k (generatedTally.getD k 0 + 1)
        continue
      if isInstanceCore env n then
        exInstance := exInstance + 1
        continue
      let r ← withCurrHeartbeats <|
        withTheReader Core.Context (fun c => { c with maxHeartbeats := 200000 * 1000 }) <|
          Core.tryCatchRuntimeEx (some <$> (classify tv.type).run') (fun _ => pure none)
      match r with
      | none =>
        exError := exError + 1
        errNames := errNames.push (toString n)
      | some none => exNotProp := exNotProp + 1
      | some (some sh) =>
        hist := hist.modify (min sh.hyps 5) (· + 1)
        if sh.hyps ≥ 2 then
          let name := toString n
          let lastComp := match n with
            | .str _ s => s
            | .num _ k => toString k
            | .anonymous => ""
          unsorted := unsorted.push {
            name, module := toString mod, stratum, shape := sh, digest := sha256Hex name,
            deprecated := Linter.isDeprecated env n,
            noRange := (← findDeclarationRangesCore? n).isNone, lastComp }
  let frame := unsorted.qsort Row.lt
  -- strata as (name, start, size), in stratum order
  let mut strata : Array (String × Nat × Nat) := #[]
  for k in [0:frame.size] do
    let s := frame[k]!.stratum
    match strata.back? with
    | some (s', st, sz) =>
      if s' == s then strata := strata.pop.push (s', st, sz + 1)
      else strata := strata.push (s, k, 1)
    | none => strata := strata.push (s, k, 1)
  let sizes := strata.map fun (s, _, sz) => (s, sz)
  if frame.size < sampleTotal then
    throwError "frame has {frame.size} theorems, fewer than {sampleTotal}"
  let alloc := allocate sizes sampleTotal stratumFloor
  let allocSum := alloc.foldl (· + ·) 0
  unless allocSum == sampleTotal do
    throwError "allocation sums to {allocSum}, not {sampleTotal}"
  for j in [0:sizes.size] do
    let (nm, sz) := sizes[j]!
    unless alloc[j]! ≤ sz && min stratumFloor sz ≤ alloc[j]! do
      throwError "allocation {alloc[j]!} for stratum {nm} of size {sz} is out of bounds"
  let mut sample : Array Row := #[]
  let mut sampleDepByStratum : Array Nat := #[]
  let mut frameDepByStratum : Array Nat := #[]
  for j in [0:strata.size] do
    let (_, st, sz) := strata[j]!
    let mut fd := 0
    for k in [st:st + sz] do
      if frame[k]!.shape.dependent then fd := fd + 1
    frameDepByStratum := frameDepByStratum.push fd
    let mut sd := 0
    for k in [st:st + alloc[j]!] do
      sample := sample.push frame[k]!
      if frame[k]!.shape.dependent then sd := sd + 1
    sampleDepByStratum := sampleDepByStratum.push sd
  let outDir := (← IO.getEnv "ANCHOR_CENSUS_OUT").getD "AnchorTest/Census"
  IO.FS.createDirAll outDir
  let header := "name\tmodule\tstratum\thypotheses\tmodel_binders\tdependent\n"
  let mut tsv := header
  for r in sample do
    tsv := tsv ++ r.tsv ++ "\n"
  IO.FS.writeFile (outDir ++ "/mathlib_sample_2000.tsv") tsv
  IO.FS.withFile (outDir ++ "/mathlib_frame.tsv") .write fun h => do
    h.putStr "name\tmodule\tstratum\thypotheses\tmodel_binders\tdependent\tsha256\n"
    for r in frame do
      h.putStr (r.tsv ++ "\t" ++ r.digest ++ "\n")
  -- summary
  let count (rows : Array Row) (p : Row → Bool) : Nat := rows.foldl (fun c r => if p r then c + 1 else c) 0
  let frameDep := count frame (·.shape.dependent)
  let sampleDep := count sample (·.shape.dependent)
  let instDrop (r : Row) : Bool := r.shape.hyps - r.shape.instHyps < 2
  let noRangeRows := frame.filter (·.noRange)
  let mut tally : Std.HashMap String Nat := {}
  for r in noRangeRows do
    tally := tally.insert r.lastComp (tally.getD r.lastComp 0 + 1)
  let ranked (m : Std.HashMap String Nat) : String :=
    let arr := m.toArray.qsort fun a b => a.2 > b.2 || (a.2 == b.2 && a.1 < b.1)
    ", ".intercalate (arr.toList.take 20 |>.map fun (k, v) => s!"{k} {v}")
  let specName (r : Row) : Bool := (r.name.splitOn ".").any (·.endsWith "_spec")
  let eqName (r : Row) : Bool := (r.name.splitOn "eq_").length > 1
  let specRows := frame.filter specName
  let eqRows := frame.filter eqName
  let eligible := hist.foldl (· + ·) 0
  let quota (sz : Nat) : String :=
    let q := (sampleTotal * 10 * sz + frame.size / 2) / frame.size
    s!"{q / 10}.{q % 10}"
  let mut s := ""
  s := s ++ "Anchor census: Mathlib sample of 2,000 theorems with at least two hypotheses\n"
  s := s ++ s!"Lean {Lean.versionString}\n"
  s := s ++ s!"SHA-256 self-test: {sha256Vectors.length} of {sha256Vectors.length} standard vectors matched\n\n"
  s := s ++ "Scan\n"
  s := s ++ s!"  Mathlib modules scanned: {modsScanned}\n"
  s := s ++ s!"  Constants in those modules: {constsScanned}\n"
  s := s ++ s!"  Theorems scanned: {thmsScanned}\n"
  s := s ++ s!"  Excluded, internal or private name: {exInternal} ({ranked internalTally})\n"
  s := s ++ s!"  Excluded, generated by the elaborator: {exGenerated} ({ranked generatedTally})\n"
  s := s ++ s!"  Excluded, instance: {exInstance}\n"
  s := s ++ s!"  Excluded, type not a Prop: {exNotProp}\n"
  s := s ++ s!"  Excluded, classification failed: {exError}{if errNames.isEmpty then "" else " (" ++ ", ".intercalate errNames.toList ++ ")"}\n"
  s := s ++ s!"  Eligible theorems: {eligible}\n"
  s := s ++ s!"  Hypothesis count over eligible theorems: 0: {hist[0]!}, 1: {hist[1]!}, 2: {hist[2]!}, 3: {hist[3]!}, 4: {hist[4]!}, 5 or more: {hist[5]!}\n\n"
  s := s ++ "Frame (eligible theorems with at least two hypotheses)\n"
  s := s ++ s!"  Frame size: {frame.size}\n"
  s := s ++ s!"  Strata: {strata.size}\n"
  s := s ++ s!"  Dependent in frame: {frac frameDep frame.size}\n"
  s := s ++ s!"  Dependent in sample: {frac sampleDep sample.size}\n"
  s := s ++ s!"  Deprecated aliases, kept: frame {count frame (·.deprecated)}, sample {count sample (·.deprecated)}\n"
  s := s ++ s!"  Below two hypotheses if Prop-valued instance binders were counted as model: frame {count frame instDrop}, sample {count sample instDrop}\n"
  s := s ++ s!"  Names with a component ending in \"_spec\", kept: frame {specRows.size}, sample {count sample specName}; first three: {", ".intercalate (specRows.toList.take 3 |>.map (·.name))}\n"
  s := s ++ s!"  Names containing \"eq_\", kept: frame {eqRows.size}, sample {count sample eqName}; first three: {", ".intercalate (eqRows.toList.take 3 |>.map (·.name))}\n"
  s := s ++ s!"  Frame theorems with no declaration range: {noRangeRows.size}{if noRangeRows.isEmpty then "" else "; most common last components: " ++ ranked tally}\n\n"
  s := s ++ "Strata (frame size, dependent in frame, proportional quota, allocation, dependent in sample)\n"
  for j in [0:strata.size] do
    let (nm, _, sz) := strata[j]!
    s := s ++ s!"  {padR nm 24}{padL (toString sz) 8}{padL (toString frameDepByStratum[j]!) 8}{padL (quota sz) 9}{padL (toString alloc[j]!) 7}{padL (toString sampleDepByStratum[j]!) 7}\n"
  s := s ++ s!"  {padR "total" 24}{padL (toString frame.size) 8}{padL (toString frameDep) 8}{padL (toString sampleTotal) 9}{padL (toString allocSum) 7}{padL (toString sampleDep) 7}\n\n"
  s := s ++ "Allocation: a stratum whose proportional share of the units not yet assigned is below\n"
  s := s ++ "min(10, n_s) is held at that floor; this repeats until no stratum changes. The other\n"
  s := s ++ "strata share the remaining units in proportion to size: the floor of each exact share,\n"
  s := s ++ "then one more unit each to the largest remainders (ties: larger stratum, then name).\n"
  s := s ++ "Selection: within a stratum, lowest SHA-256 of the UTF-8 name as printed, no salt.\n\n"
  s := s ++ "First three sample rows with digests (check with printf '%s' NAME | sha256sum)\n"
  for r in sample.toList.take 3 do
    s := s ++ s!"  {r.digest}  {r.name}\n"
  IO.FS.writeFile (outDir ++ "/mathlib_sample_summary.txt") s
  IO.println s

end AnchorTest.Census.MathlibSample

set_option maxHeartbeats 0 in
#eval AnchorTest.Census.MathlibSample.run
